// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFTgCMDRWCGoW2SK-Dk6rbDQdIh1j4g6s',
    appId: '1:102614265328:web:37edc11690db16e0598135',
    messagingSenderId: '102614265328',
    projectId: 'login-auth-21ee2',
    authDomain: 'login-auth-21ee2.firebaseapp.com',
    storageBucket: 'login-auth-21ee2.appspot.com',
    measurementId: 'G-5YTFL589MK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGklX__JyTVsIaMj1O7Jpx7UKbpQueGsk',
    appId: '1:102614265328:android:2de505b0cf9637c6598135',
    messagingSenderId: '102614265328',
    projectId: 'login-auth-21ee2',
    storageBucket: 'login-auth-21ee2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl8b5_aevT4gRSxg1-cNmoT_G0BxFTeu8',
    appId: '1:102614265328:ios:d92321fe952fde04598135',
    messagingSenderId: '102614265328',
    projectId: 'login-auth-21ee2',
    storageBucket: 'login-auth-21ee2.appspot.com',
    iosBundleId: 'com.example.loginAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl8b5_aevT4gRSxg1-cNmoT_G0BxFTeu8',
    appId: '1:102614265328:ios:949bba73f3a51c30598135',
    messagingSenderId: '102614265328',
    projectId: 'login-auth-21ee2',
    storageBucket: 'login-auth-21ee2.appspot.com',
    iosBundleId: 'com.example.loginAuthentication.RunnerTests',
  );
}
